### ISSUE TITLE
A8 nodes deployment failure

### ISSUE THREAD

**Issue by druzmieres** [iot-lab/iot-lab#226] opened 2018-06-26 20:42 UTC
I've been trying to run an experiment using A8 nodes but the deployment is failing every time. I tried having a successful deployment with and without an association and it fails in both cases. It fails in the old web portal and in the new one too. M3 nodes seem to be working correctly.

**Comment by fsaintma** [comment] 2018-06-27 07:28
Hi
Indeed I have just saw the testbed logs and it seems that we encountered some network issues. I launch an experiment this morning and it works normally. Should you retry again ?
Sorry for the inconvenience.
Best regards.

**Comment by druzmieres** [comment] 2018-07-03 15:03
Hi,
Are you having the same networks issues again? I'm having the same problem now.
Regards.

**Comment by fsaintma** [comment] 2018-07-04 07:22
Hi @druzmieres , I have just investigated again and I found that the problem is only for your account. So the last time I made a mistake and the problem seems to be due to your home directory on the Grenoble site. Indeed the A8 directory was removed (by you ?) and it was mandatory for A8 experiment nodes setup. So I have just created it again with good permissions and I hope that it will fix your problem.

**Comment by druzmieres** [comment] 2018-07-07 22:18
@fsaintma Thank you, I'm new at this and probably deleted that folder when I was trying to solve some other issue. I didn't know the folder was mandatory. Actually, I thought it was automatically generated.

Now I can finally run some experiments. :)

**Comment by aabadie** [comment] 2019-06-17 10:01
Seems that this is fixed. Closing.

**Closed by aabadie** 2019-06-17 10:01 UTC
